# Generated by Django 5.0.3 on 2024-03-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0003_blogpost_alter_doctor_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='last_name',
        ),
    ]
